name: CI

on:
  push:
    branches: [ azure-pipelines ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'anhntk54/check_web'
          destination-github-username: 'anhntk54/'
          destination-repository-name: 'anhntk54/check_web'
          user-email: anhntk54@gmail.com
          target-branch: master
